apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rv3k
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rv3k
    app.kubernetes.io/part-of: integ-app-fbie
  name: hacbs-test-project-rv3k
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rv3k
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rv3k
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-wwuq-tenant/integ-app-fbie/hacbs-test-project-rv3k@sha256:1cbfd07048ba4a59822e1b2e0e4d7d30eb531c08bb82313b56022ca9d6ff0b06
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
